Adds shared fs snap support
Added support for gluster-backed shared filesystem support (alpha)

diff --git a/files/es-snapper b/files/es-snapper
--- a/files/es-snapper
+++ b/files/es-snapper
@@ -11,13 +11,25 @@ usage() {
   echo "  -i INDICES : coma-separated list of indices (default: all indices)"
   echo "  -s SNAPSHOT: snapshot name (default: date formatted as YYYYMMDDHHMMSS)"
   echo "  -b BUCKET  : creates repository in S3 BUCKET if it does not exist (default: skip)"
+  echo "  -f PATH    : creates repository on shared (locally mounted) filesystem (default: skip)"
   echo
 }
 
-check_and_create_repository() {
+check_and_create_s3_repository() {
   # Set host
   URI="http://${HOST}:${PORT}/_snapshot/${REPOSITORY}"
   RESULT=$(curl -sX PUT ${URI} --data "{ \"type\": \"s3\", \"settings\": { \"bucket\": \"${BUCKET}\" }}")
+
+  if ! echo ${RESULT} | grep -F "acknowledged\":true" > /dev/null; then
+    echo -e "\nError: Unable to create repository: \n"
+    echo ${RESULT}
+  fi
+}
+
+check_and_create_fs_repository() {
+  # Set host
+  URI="http://${HOST}:${PORT}/_snapshot/${REPOSITORY}"
+  RESULT=$(curl -sX PUT ${URI} --data "{ \"type\": \"fs\", \"settings\": { \"location\": \"${FILESYSTEM}\", \"compress\": \"true\"}}")
 
   if ! echo ${RESULT} | grep -F "acknowledged\":true" > /dev/null; then
     echo -e "\nError: Unable to create repository: \n"
@@ -42,7 +54,7 @@ snapshot() {
   exit 1
 }
 
-while getopts ":h:p:r:s:i:b:" opt; do
+while getopts ":h:p:r:s:i:b:f:" opt; do
   case $opt in
     h)
       HOST=$OPTARG
@@ -61,6 +73,9 @@ while getopts ":h:p:r:s:i:b:" opt; do
       ;;
     b)
       BUCKET=$OPTARG
+      ;;
+    f)
+      FILESYSTEM=$OPTARG
       ;;
     \?)
       echo "Invalid option: -$OPTARG" >&2
@@ -84,7 +99,11 @@ if [ -z $REPOSITORY ]; then
 fi
 
 if [ ! -z $BUCKET ]; then
-  check_and_create_repository
+  check_and_create_s3_repository
+fi
+
+if [ ! -z $FILESYSTEM ]; then
+  check_and_create_fs_repository
 fi
 
 snapshot
